# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Forge Wizard' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Forge Wizard
	pod 'UIColor_Hex_Swift', :git => 'https://github.com/yeahdongcn/UIColor-Hex-Swift.git', :tag => '4.0.0'
        pod 'SwiftyJSON'
        pod 'Alamofire'
    	pod 'AlamofireImage'


end
